name: "Plan and Deploy"
on:
  workflow_dispatch:

permissions:
  id-token: write # This is required for aws oidc connection
  contents: read # This is required for actions/checkout
  pull-requests: write # This is required for gh bot to comment PR

env:
  environment: devl
  TF_LOG: INFO
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
  AWS_TF_STATE_BUCKET_NAME: ${{ secrets.AWS_TF_STATE_BUCKET_NAME }}
  AWS_TF_STATE_BUCKET_KEY_NAME: ${{ secrets.AWS_TF_STATE_BUCKET_KEY_NAME }}

jobs:
  plan-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Dev
        uses: subhamay-cloudworks/terraform-ci-cd/.github/workflows/terraform-plan-oidc.yaml@main
        with:
          tfvars_filename: devl.terraform.tfvars
          github_env: devl
          aws_region: ${AWS_REGION}
          aws_role_arn: $AWS_ROLE_ARN
          aws_tf_state_bucket_name: $AWS_TF_STATE_BUCKET_NAME
          aws_tf_state_bucket_key_name: $AWS_TF_STATE_BUCKET_KEY_NAME

