name: "Plan and Deploy"
on:
  workflow_dispatch:

jobs:
  plan-dev:
    uses: subhamay-cloudworks/terraform-ci-cd/.github/workflows/terraform-plan-oidc.yaml@main
    with:
      tfvars_filename: devl.terraform.tfvars
      github_env: devl

