name: "Plan and Deploy"
on:
  workflow_dispatch:

permissions:
  id-token: write # This is required for aws oidc connection
  contents: read # This is required for actions/checkout
  pull-requests: write # This is required for gh bot to comment PR

jobs:
  plan-dev:
    uses: subhamay-cloudworks/terraform-ci-cd/.github/workflows/terraform-plan-oidc.yaml@main
    with:
      tfvars_filename: devl.terraform.tfvars
      github_env: devl
      aws_region: us-east-1
      aws_role_arn: arn:aws:iam::237376087602:role/CloudWorksGitHubOIDCRole
      aws_tf_state_bucket_name: subhamay-terraform-remote-state-237376087602-devl-us-east-1
      aws_tf_state_bucket_key_name: 0000-terraform-cicd/devl/terraform.tfstate

